name: major_craft_application
description: Flutter MajorCraft Application.
publish_to: "none"
version: 1.0.0+1

environment:
    sdk: ">=3.0.0 <4.0.0"

dependencies:
    auto_route: ^7.8.2
    auto_route_generator: ^7.3.1
    auto_size_text: ^3.0.0
    auto_size_text_field: ^2.2.2
    bloc: ^8.1.1
    change_app_package_name: ^1.1.0
    connectivity_plus: ^5.0.2
    cross_file: ^0.3.3+8
    cupertino_icons: ^1.0.2
    dio: ^5.0.3
    equatable: ^2.0.0
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.2
    flutter_easyloading: ^3.0.5
    flutter_html: ^3.0.0-beta.2
    flutter_launcher_icons: ^0.13.1
    flutter_localizations:
        sdk: flutter
    flutter_native_splash: ^2.2.18
    flutter_screenutil: ^5.6.0
    flutter_secure_storage: ^9.0.0
    flutter_svg: ^2.0.2
    flutter_widget_from_html: ^0.14.9
    fluttertoast: ^8.2.4
    freezed_annotation: ^2.2.0
    get_it: ^7.6.4
    google_fonts: ^4.0.3
    http: ^0.13.5
    image_picker: ^1.0.5
    injectable: ^2.1.0
    intl: ^0.19.0
    json_annotation: ^4.8.1
    just_the_tooltip: ^0.0.12
    jwt_decoder: ^2.0.1
    logger: ^2.0.2
    meta: ^1.8.0
    page_transition: ^2.1.0
    path_provider: ^2.1.1
    pinput: ^3.0.1
    provider: ^6.1.1
    rename_app: ^1.3.1
    retrofit: ^4.0.1
    smartstruct: ^1.4.0
    smooth_page_indicator: ^1.1.0
    visibility_detector: ^0.4.0+2

dev_dependencies:
    build_runner: ^2.4.6
    dart_code_metrics: ^5.6.0
    flutter_gen_runner: ^5.2.0
    flutter_lints: ^3.0.1
    flutter_test:
        sdk: flutter
    freezed: ^2.2.0
    injectable_generator: ^2.1.4
    json_serializable: ^6.5.4
    retrofit_generator: ^8.0.6
    smartstruct_generator: ^1.4.0

# Assets Generator
flutter_gen:
    output: lib/resources
    line_length: 120
    # Optional
    integrations:
        flutter_svg: true
        flare_flutter: true
        rive: true
        lottie: true
    fonts:
        enabled: false

# Native Splash
flutter_native_splash:
    color: "#1D3061"
    image: assets/major_logo_splash_bigger_font.png
    android: true
    ios: true
    android_12:
        color: "#1D3061"
        image: assets/major_logo_splash_bigger_font.png
        android: true
        ios: true

# App Icon
flutter_launcher_icons:
    android: "launcher_icon"
    ios: true
    image_path: "assets/major_logo_icon_bigger_font.png"
    min_sdk_android: 21 # android min sdk min:16, default 21
    remove_alpha_ios: true

# Internationalization and Localization Generator
flutter_intl:
    enabled: true
    class_name: Lang
    arb_dir: lib/core/localization
    output_dir: lib/core/localization/generated

flutter:
    uses-material-design: true

    assets:
        - "assets/"
        - "assets/images/"
        - "assets/icons/"
